FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

ENV VITE_API_URL=/api/v1

COPY . .
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /etc/nginx/ssl && \
    mkdir -p /usr/share/nginx/uploads && \
    chown -R nginx:nginx /usr/share/nginx/uploads && \
    chmod -R 755 /usr/share/nginx/uploads

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
